version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=associacao
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: associacao
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./meu_database.sql:/docker-entrypoint-initdb.d/meu_database.sql  # Script SQL de inicialização

volumes:
  db_data:
